spring:
  application:
    name: concert-mania
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul

jwt:
  secret:
    key: Y29uY2VydC1tYW5pYS1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleS1mb3ItY29uY2VydC1tYW5pYS1hcHA=

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.cache: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,httptrace
  endpoint:
    health:
      show-details: always
