server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-mysql:3306/concertMania?useSSL=true&serverTimezone=Asia/Seoul
    username: prod_user
    password: prod_pass
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: prod-redis
    port: 6379

  cache:
    type: redis
